//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stock")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub currency: String,
    pub exchange_id: String,
    pub mic_code: String,
    pub country: String,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::exchange::Entity",
        from = "Column::ExchangeId",
        to = "super::exchange::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Exchange,
}

impl Related<super::exchange::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exchange.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
