//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::StockType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "stock")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub country: String,
    pub r#type: StockType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stock_exchange::Entity")]
    StockExchange,
}

impl Related<super::stock_exchange::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockExchange.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
