[package]
name = "rust-axum-intro"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "api", "model" ]

[dependencies]
api = { path = "api" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
