[package]
name = "rust-axum-intro"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "migration", "model" ]

[dependencies]
model = { path = "model" }
reqwest = { version = "^0.11", features = ["json"] }
serde = "^1.0.192"
tokio = { version = "^1.34.0", features = ["full"] }
